#if !canImport(ObjectiveC)
import XCTest

extension BulletPhysicsClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BulletPhysicsClientTests = [
        ("testApplyExternalForce", testApplyExternalForce),
        ("testApplyExternalTorque", testApplyExternalTorque),
        ("testCastMultipleRays", testCastMultipleRays),
        ("testCastSingleRay", testCastSingleRay),
        ("testCreateCollisionShapes", testCreateCollisionShapes),
        ("testCreateMultiBody", testCreateMultiBody),
        ("testGetActualPlacement", testGetActualPlacement),
        ("testRemoveCollisionShape", testRemoveCollisionShape),
        ("testSetParameters", testSetParameters),
        ("testStepSimulation", testStepSimulation)
    ]
}

extension SIMDUnsafeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SIMDUnsafeTests = [
        ("testSIMD2UnsafePointer", testSIMD2UnsafePointer),
        ("testSIMD3UnsafePointer", testSIMD3UnsafePointer),
        ("testSIMD4UnsafePointer", testSIMD4UnsafePointer),
        ("testSIMDArrayPointer", testSIMDArrayPointer)
    ]
}

extension SwiftBulletTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftBulletTests = [
        ("testApplyExternalForce", testApplyExternalForce),
        ("testApplyExternalTorque", testApplyExternalTorque),
        ("testBatchRayCast", testBatchRayCast),
        ("testCreateRemoveCollisionShape", testCreateRemoveCollisionShape),
        ("testNumBodies", testNumBodies),
        ("testResetSimulation", testResetSimulation),
        ("testSimpleGravitySim", testSimpleGravitySim),
        ("testSingleRayCast", testSingleRayCast)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BulletPhysicsClientTests.__allTests__BulletPhysicsClientTests),
        testCase(SIMDUnsafeTests.__allTests__SIMDUnsafeTests),
        testCase(SwiftBulletTests.__allTests__SwiftBulletTests)
    ]
}
#endif
