name: macOS

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  macOS-build-release:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ["12.4"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Restore cached Homebrew dependencies
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/Library/Caches/Homebrew/bullet--*
            ~/Library/Caches/Homebrew/downloads/*--bullet-*
          key: ${{ runner.os }}-brew-bullet-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: ${{ runner.os }}-brew-bullet-
      - name: Restore cached SPM dependencies
        uses: actions/cache@v2.1.6
        with:
          path: |
            .build/repositories
            .build/checkouts
          key: ${{ runner.os }}-spm-deps-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-deps-
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Install dependencies
        run: |
          brew install bullet
      - name: Test
        run: swift test --skip-update --enable-test-discovery
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Build Release
        run: make build-release
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v2.2.3
        with:
          name: build-artifacts-${{ matrix.xcode }}-${{ github.run_id }}
          path: |
            *.lcov
            .build/*.yaml
            .build/debug/*.a
            .build/debug/*.so
            .build/debug/*.dylib
            .build/debug/*.dSYM 
            .build/debug/*.json
            .build/release/*.a
            .build/release/*.so
            .build/release/*.dylib
            .build/release/*.dSYM 
            .build/release/*.json
